### ISSUE TITLE
Improve punctuation in docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md

### ISSUE THREAD

**Issue by gpang** [Alluxio/new-contributor-tasks#128]
In docs/en/Configuring-Alluxio-with-Azure-Blob-Store.md, in the Initial Setup section, the last sentence is missing a period. A period should be added to this sentence:

`For more information about Azure storage account, Please see here`

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/6415
