### ISSUE TITLE
Supply the variable name to Preconditions.checkNotNull in alluxio.worker.block.allocator.MaxFreeAllocator#MaxFreeAllocator

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#159]
Change

```java
    mManagerView = Preconditions.checkNotNull(view);
```

to

```java
    mManagerView = Preconditions.checkNotNull(view, "view");
```

**Comment by jarsar** [comment]
可以解释下Supply the variable name to Preconditions.checkNotNull alluxio.worker.block.allocator.MaxFreeAllocator#MaxFreeAllocator的意思吗，我在MaxFreeAllocator.java中发现了两段mManagerView = Preconditions.checkNotNull(view);
