### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getStartTimeMs

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#172]
change

    return RestUtils.call(new RestUtils.RestCallable<Long>() {
       @Override
       public Long call() throws Exception {
           return mMasterProcess.getStartTimeMs();
       }
      });

to

    return RestUtils.call(() -> mMasterProcess.getStartTimeMs());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7375
