### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getUptimeMs

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#175]
change

    return RestUtils.call(new RestUtils.RestCallable<Long>() {
      @Override
      public Long call() throws Exception {
        return mMasterProcess.getUptimeMs();
      }
    });

to

    return RestUtils.call(() -> mMasterProcess.getUptimeMs());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7050
