### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getCapacityBytes

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#180]
change

    return RestUtils.call(new RestUtils.RestCallable<Long>() {
       @Override
       public Long call() throws Exception {
           return mBlockMaster.getCapacityBytes();
       }
     });

to

    return RestUtils.call(() -> mBlockMaster.getCapacityBytes());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7012
