### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getUsedBytes

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#186]
change

     return RestUtils.call(new RestUtils.RestCallable<Long>() {
        @Override
        public Long call() throws Exception {
            return mBlockMaster.getUsedBytes();
        }
      });

to

      return RestUtils.call(() -> mBlockMaster.getUsedBytes());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7180
