### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getFreeBytes

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#190]
change

    return RestUtils.call(new RestUtils.RestCallable<Long>() {
      @Override
      public Long call() throws Exception {
        return mBlockMaster.getCapacityBytes() - mBlockMaster.getUsedBytes();
      }
    });

to

    return RestUtils.call(() -> mBlockMaster.getCapacityBytes() - mBlockMaster.getUsedBytes());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7122
