### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getUfsCapacityBytes

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#192]
change

    return RestUtils.call(new RestUtils.RestCallable<Long>() {
      @Override
      public Long call() throws Exception {
        return mUfs.getSpace(mUfsRoot, UnderFileSystem.SpaceType.SPACE_TOTAL);
      }
    });

to

    return RestUtils.call(() -> mUfs.getSpace(mUfsRoot, UnderFileSystem.SpaceType.SPACE_TOTAL));

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7170
