### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getCapacityBytesOnTiers

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#195]
change

    return RestUtils.call(new RestUtils.RestCallable<Map<String, Long>>() {
          @Override
          public Map<String, Long> call() throws Exception {
            SortedMap<String, Long> capacityBytesOnTiers = new TreeMap<>(getTierAliasComparator());
            for (Map.Entry<String, Long> tierBytes : mBlockMaster.getTotalBytesOnTiers().entrySet()) {
              capacityBytesOnTiers.put(tierBytes.getKey(), tierBytes.getValue());
            }
            return capacityBytesOnTiers;
         }
      });

to

    return RestUtils.call((RestUtils.RestCallable<Map<String, Long>>) () -> {
      SortedMap<String, Long> capacityBytesOnTiers = new TreeMap<>(getTierAliasComparator());
      for (Map.Entry<String, Long> tierBytes : mBlockMaster.getTotalBytesOnTiers().entrySet()) {
        capacityBytesOnTiers.put(tierBytes.getKey(), tierBytes.getValue());
      }
      return capacityBytesOnTiers;
    });

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7034
