### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getUsedBytesOnTiers

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#196]
change

    return RestUtils.call(new RestUtils.RestCallable<Map<String, Long>>() {
          @Override
          public Map<String, Long> call() throws Exception {
            SortedMap<String, Long> usedBytesOnTiers = new TreeMap<>(getTierAliasComparator());
            for (Map.Entry<String, Long> tierBytes : mBlockMaster.getUsedBytesOnTiers().entrySet()) {
              usedBytesOnTiers.put(tierBytes.getKey(), tierBytes.getValue());
            }
            return usedBytesOnTiers;
          }
     });

to

    return RestUtils.call((RestUtils.RestCallable<Map<String, Long>>) () -> {
      SortedMap<String, Long> usedBytesOnTiers = new TreeMap<>(getTierAliasComparator());
      for (Map.Entry<String, Long> tierBytes : mBlockMaster.getUsedBytesOnTiers().entrySet()) {
        usedBytesOnTiers.put(tierBytes.getKey(), tierBytes.getValue());
      }
      return usedBytesOnTiers;
    });

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7135
