### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getWorkerCount

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#197]
change

    return RestUtils.call(new RestUtils.RestCallable<Integer>() {
      @Override
      public Integer call() throws Exception {
        return mBlockMaster.getWorkerCount();
      }
    });

to

    return RestUtils.call(() -> mBlockMaster.getWorkerCount());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7156
