### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#getWorkerInfoList

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#198]
change

    return RestUtils.call(new RestUtils.RestCallable<List<WorkerInfo>>() {
      @Override
      public List<WorkerInfo> call() throws Exception {
        return mBlockMaster.getWorkerInfoList();
      }
    });

to

    return RestUtils.call(() -> mBlockMaster.getWorkerInfoList());

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7171
