### ISSUE TITLE
Java 8 Improvement: replace anonymous type with lambda in alluxio.master.file.AlluxioMasterRestServiceHandler#logLevel

### ISSUE THREAD

**Issue by xiaole-max** [Alluxio/new-contributor-tasks#199]
change

    return RestUtils.call(new RestUtils.RestCallable<LogInfo>() {
      @Override
      public LogInfo call() throws Exception {
        return LogUtils.setLogLevel(logName, level);
      }
    });

to

    return RestUtils.call(() -> LogUtils.setLogLevel(logName, level));

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/pull/7124
