### ISSUE TITLE
[DOCFIX] Inline documentation snippets in docs/en/Configuring-Alluxio-with-NFS.md

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#258]
**For example**

Replace
```
{% include Configuring-Alluxio-with-NFS/underfs-address.md %}
```

with the real content

<pre>
```
properties
alluxio.underfs.address=/mnt/nfs
```
</pre>

These files are located in `docs/_includes`.

**Comment by jzyhywxz** [comment]
hello, @newnius . I cannot find the sentence `{% include Configuring-Alluxio-with-NFS/underfs-address.md %}` in file `docs/en/Configuring-Alluxio-with-NFS.md`! What can I do?

**Comment by newnius** [comment]
Please note the **For example**

It means you have to find all lines like {% include XXX.md %} in file `docs/en/Configuring-Alluxio-with-NFS.md` and replace them with the real contents.

**Comment by jzyhywxz** [comment]
@newnius You are right, It's my false, I'll just do it! Thank you very mach!
