### ISSUE TITLE
[DOCFIX] Inline documentation snippets in docs/cn/Command-Line-Interface.md

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#266]
**For example**

Replace
```
{% include Configuring-Alluxio-with-NFS/underfs-address.md %}
```

with the real content

<pre>
```properties
alluxio.underfs.address=/mnt/nfs
```
</pre>

These files are located in `docs/_includes`.

**Comment by starry-sky6688** [comment]
你好，Command-Line-Interface.md文件里没有需要替换的这句话呀，请问该怎么办呢？

**Comment by newnius** [comment]
请看开头的 **For example**

照猫画虎

**Comment by starry-sky6688** [comment]
那我只要随便替换掉一句话就可以了吗？

**Comment by newnius** [comment]
替换全部类似行或者一部分，都可以。看你心情

**Comment by starry-sky6688** [comment]
好的，谢谢！

**Comment by starry-sky6688** [comment]
你好，请问Create PR时，它说我可以被自动merge，然后没有给我提供写PR标题和内容的地方，怎么办呢，可以直接Create吗？

**Comment by newnius** [comment]
相关的截图？

**Comment by starry-sky6688** [comment]
![2g z y 0eowy5bgo8igs 2h](https://user-images.githubusercontent.com/38175678/46913172-d9381c80-cfba-11e8-9d9b-d76d972cad81.png)

**Comment by starry-sky6688** [comment]
![image](https://user-images.githubusercontent.com/38175678/46913313-6aa88e00-cfbd-11e8-83ed-71509a1d8e3a.png)

**Comment by newnius** [comment]
没有conflict，你直接create，pr说明在后续步骤
