### ISSUE TITLE
Fix formatting after Nullable in DefaultFileSystemMaster

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/new-contributor-tasks#27]
In `core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java`, we have the signature

```java
private FileSystemMasterAuditContext createAuditContext(String command, AlluxioURI srcPath,
    @Nullable  AlluxioURI dstPath, @Nullable  Inode srcInode) throws AccessControlException {
```

There are two spaces after each `@Nullable` annotation, but there should be only one

**Comment by roosteracham** [comment]
#https://github.com/Alluxio/alluxio/pull/6262
