### ISSUE TITLE
[SMALLFIX] Improve comment style in alluxio.client.file.FileOutStream

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#276]
Comments which start with a capital letter should end with a period.

**Comment by NaivePawn** [comment]
I cannot find the file alluxio.client.file.FileOutStream.

**Comment by newnius** [comment]
https://github.com/Alluxio/alluxio/blob/db4075e8f8d636dbf5d479176c7620551a361b8c/core/client/fs/src/main/java/alluxio/client/file/FileOutStream.java

**Comment by NaivePawn** [comment]
Okay, thank you!

**Comment by NaivePawn** [comment]
mvn clean install -DskipTests

[ERROR] Plugin org.apache.maven.plugins:maven-source-plugin:2.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:2.3: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:2.3 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]

**Comment by newnius** [comment]
Skip the test and create a pr directly, it is not easy to figure out what is wrong with alluxio in your computer.

**Comment by NaivePawn** [comment]
![default](https://user-images.githubusercontent.com/34669331/46913871-2969ab80-cfc8-11e8-9f79-e3037e5eeffe.JPG)

**Comment by NaivePawn** [comment]
Merged build finished. test failed 
what does this mean?

**Comment by newnius** [comment]
文件最前面一大段是自动生成的版权信息，不是代码注释，不要改

**Comment by NaivePawn** [comment]
我改回来了，还是failed

**Comment by newnius** [comment]
Test PASSed.

**Comment by NaivePawn** [comment]
ok，thank you

**Comment by NaivePawn** [comment]
这算Marged了吗
