### ISSUE TITLE
Merged build finished. Test FAILed.

### ISSUE THREAD

**Issue by Rafael-Luo** [Alluxio/new-contributor-tasks#397]
Test FAILed.
Refer to this link for build results (access rights to CI server needed):
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-Pull-Request-Builder/779/
Test FAILed.

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.986 sec <<< FAILURE! - in alluxio.server.ft.MasterFailoverIntegrationTest
failoverJournalFencingTest(alluxio.server.ft.MasterFailoverIntegrationTest)  Time elapsed: 43.689 sec  <<< ERROR!
alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ ab1e1abd757a/172.17.0.2:44472 after 32 attempts
	at alluxio.server.ft.MasterFailoverIntegrationTest.failoverJournalFencingTest(MasterFailoverIntegrationTest.java:103)

**Comment by Rafael-Luo** [comment]
没有改其他文件  然后有一个测试未通过，该如何解决呢

**Comment by newnius** [comment]
This repo is used for assigning new tasks only.
