### ISSUE TITLE
【smallfix】one problem to be  confirmed in the first assignment 

### ISSUE THREAD

**Issue by lixiawei** [Alluxio/new-contributor-tasks#398]
助教，请问我的request是只需要在这新建一个文件Thrift.md 然后在里面写上"使用Port安装Thrift"就可以提交tijiaotijiao 了吗？https://github.com/Alluxio/new-contributor-tasks/issues/363

**Comment by lixiawei** [comment]
@newnius

**Comment by newnius** [comment]
Please do not post your question here. This repo is for assigning tasks only.

**Comment by newnius** [comment]
The file path has changed, find it and then continue.
