### ISSUE TITLE
Update class comments for DefaultBlockMaster

### ISSUE THREAD

**Issue by gpang** [Alluxio/new-contributor-tasks#40]
In `/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java` for the class comments, update:

`This master manages the...`

to 

`This block master manages the...`

**Comment by FirstKayleinNJU** [comment]
I can't find /core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java. It may be core/server/src/main/java/alluxio/master/block/BlockMaster.java

**Comment by apc999** [comment]
this file is in the dir. not sure why not showing up in your local repo

https://github.com/Alluxio/alluxio/blob/master/core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java#L81
