### ISSUE TITLE
Deprecate Throwables.propagate with RuntimeException in CommonTestUtils.java

### ISSUE THREAD

**Issue by yupeng9** [Alluxio/new-contributor-tasks#41]
Guava "Throwables.propagate" is deprecated. see reasons in
https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate

This ticket modifies https://github.com/Alluxio/alluxio/blob/master/core/common/src/test/java/alluxio/CommonTestUtils.java#L109
https://github.com/Alluxio/alluxio/blob/master/core/common/src/test/java/alluxio/CommonTestUtils.java#L132
 to replace

```
throw Throwables.propagate(e);
```
or
```
Throwables.propagate(e);
```
with
```
throw new RuntimeException(e);
```
Remember also to remove the corresponding import if Throwables becomes unused
```
import com.google.common.base.Throwables;
```

**Comment by chaos-h** [comment]
I did it and this is the link to my PE:
https://github.com/Alluxio/alluxio/pull/6321
And I am confused because I did not receive a note like "sign a contribution license agreement" from  alluxio-bot, Does this means that I did not do everything right?
