### ISSUE TITLE
[SMALLFIX] Replace explicit type with argument with <> in alluxio/core/common/src/test/java/alluxio/test/util/ConcurrencyUtils.java#assertConcurrent

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#435]
Replace

```java
    final List<Throwable> exceptions = Collections.synchronizedList(new ArrayList<Throwable>());
```

with

```java
    final List<Throwable> exceptions = Collections.synchronizedList(new ArrayList<>());
```

**Comment by Wu-RhmBWT** [comment]
I only changed the file the assignment told me to do, but the test failed.

**Comment by newnius** [comment]
Please provide your PR link

**Comment by Wu-RhmBWT** [comment]
https://github.com/Alluxio/alluxio/pull/8805

**Comment by newnius** [comment]
Remove the uncessary file https://github.com/Alluxio/alluxio/pull/8805/files and re-test

**Comment by Wu-RhmBWT** [comment]
I accidentally pushed try4 after try3 had passed, what should I do?

**Comment by newnius** [comment]
Remove the uncessary files https://github.com/Alluxio/alluxio/pull/8805/files
