### ISSUE TITLE
[SMALLFIX] Use the @Nullable annotation for all methods which may return null in /alluxio/core/common/src/main/java/alluxio/collections/LockCache.java#getValNode

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#487]
Example: https://github.com/Alluxio/alluxio/pull/6105/files

**Comment by maodawang** [comment]
@newnius thank you ！./assign@maodawang

**Comment by maodawang** [comment]
@newnius Excuse me, can't find this file

**Comment by newnius** [comment]
During the upgrades, files may be moved or deleted, you can find it by searching the repo.

**Comment by shiyi23** [comment]
I  can't find this file either.
