### ISSUE TITLE
Update Web-Interface.md to reflect the latest change in UI

### ISSUE THREAD

**Issue by bf8086** [Alluxio/new-contributor-tasks#49]
Alluxio web UI is recently updated to show in-Alluxio data instead of in-memory data. Please update `/docs/en/Web-Interface.md` and replace `Files currently in the memory tier` with `Files currently in Alluxio`

**Comment by apc999** [comment]
this issue is not clear for new contributors. Can you be more specific, e.g., change which file and how? Otherwise, let's make it a more advanced in JIRA

**Comment by bf8086** [comment]
Updated.
