### ISSUE TITLE
[SMALLFIX] Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/util/executor/ControllableSchedulerTest.java

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#552]
Change

```java
import org.junit.Assert;
```

to

```java
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
```

**AND**

Update all 

```java
Assert.{{ method }}*
```

to

```java
{{ method }}*
```

**For example**

update

```java
    Assert.assertTrue(mGraph.getRoots().isEmpty());
```

to

```java
    assertTrue(mGraph.getRoots().isEmpty());
```

**Comment by newnius** [comment]
Put the static imports before non-static imports.

**Comment by zhangfy** [comment]
I want to get this task, but I find the latest version has already fixed. What can I do for this task?

**Comment by newnius** [comment]
You can choose another task or find one on [Alluxio JIRA](https://alluxio.atlassian.net/projects/ALLUXIO/issues/?filter=allissues&=)

Also, you can review the project to see what can be improved.

On GitHub, you cannot assign a issue if you are not the matainer.

**Comment by zhangfy** [comment]
@newnius Thank you, I'll look at the jira. As a newer, I looked at the [Contribution Guide](https://docs.alluxio.io/os/user/stable/en/contributor/Contributor-Getting-Started.html), maybe the doc should be modify.

**Comment by zhangfy** [comment]
@newnius By the way,how to be the maintaner? Do you have the detail steps? Thank you again!
