### ISSUE TITLE
[SMALLFIX] Use static imports for standard test utilities in /alluxio/core/common/src/test/java/alluxio/wire/BlockLocationTest.java

### ISSUE THREAD

**Issue by newnius** [Alluxio/new-contributor-tasks#560]
Change

```java
import org.junit.Assert;
```

to

```java
import static org.junit.Assert.assertEquals;
```

**AND**

Update all 

```java
Assert.{{ method }}*
```

to

```java
{{ method }}*
```

**For example**

update

```java
    Assert.assertTrue(mGraph.getRoots().isEmpty());
```

to

```java
    assertTrue(mGraph.getRoots().isEmpty());
```

**Comment by newnius** [comment]
Put the static imports before non-static imports.

**Comment by whyliyu** [comment]
How can I take this task as my NEW CONTRIBUTOR TASK; I can't find "the link Assign to yourself " as the described : 

> "Browse any of the open New Contributor Alluxio Tasks and find one that is unassigned. You can press the link Assign to yourself in order to assign the task to yourself. "

**Comment by LuQQiu** [comment]
@whyliyu  Please check the repo to see if the task is already fixed. If not, just use 
`/assign @yourName` to dynamically assign the issue to yourself. We will come up with better ways to deal with assignment later. Thanks for reporting the issue when running new contributor task.

**Comment by luozhenglin** [comment]
![image](https://user-images.githubusercontent.com/25959725/67561022-a472af80-f74e-11e9-805c-cfeac9ed4c8b.png)
i can't find " Assign to yourself"

**Comment by maobaolong** [comment]
@LuQQiu  It is not work for /assign instrument

**Comment by zhangfy** [comment]
I want to get this task, but I find the latest version has already fixed. What can I do for this task?

**Comment by zhangfy** [comment]
And I also not fount how to assign to myself...
