### ISSUE TITLE
Remove enum field alluxio.exception.ExceptionMessage#NO_WORKER_AVAILABLE_ON_ADDRESS

### ISSUE THREAD

**Issue by apc999** [Alluxio/new-contributor-tasks#574]
https://github.com/Alluxio/alluxio/blob/4cc09dd917ce6d0397bd277f9fe605e7d1f4ddbf/core/common/src/main/java/alluxio/exception/ExceptionMessage.java#L45

Remove this enum field which is not used

**Comment by bf8086** [comment]
@apc999 Can we close this issue?
