### ISSUE TITLE
Remove enum field alluxio.exception.ExceptionMessage#LOCK_RECORD_NOT_FOUND_FOR_BLOCK_AND_SESSION

### ISSUE THREAD

**Issue by apc999** [Alluxio/new-contributor-tasks#575]
https://github.com/Alluxio/alluxio/blob/4cc09dd917ce6d0397bd277f9fe605e7d1f4ddbf/core/common/src/main/java/alluxio/exception/ExceptionMessage.java#L55

Remove this enum field which is no used

**Comment by BUPTAnderson** [comment]
assign @BUPTAnderson
