### ISSUE TITLE
Remove enum field alluxio.exception.ExceptionMessage#INSTREAM_CANNOT_SKIP

### ISSUE THREAD

**Issue by apc999** [Alluxio/new-contributor-tasks#579]
https://github.com/Alluxio/alluxio/blob/4cc09dd917ce6d0397bd277f9fe605e7d1f4ddbf/core/common/src/main/java/alluxio/exception/ExceptionMessage.java#L73

Remove this unused enum field

**Comment by BUPTAnderson** [comment]
assign @BUPTAnderson
