### ISSUE TITLE
Change worker fuse helm yaml files examples to auto generated by scripts

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/new-contributor-tasks#587]
Prerequisites:
1. Alluxio POSIX API knowledge https://docs.alluxio.io/os/user/stable/en/api/POSIX-API.html
2. Kubernetes, docker knowledge https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html
It will be better if you can test out your changes on the actual kubernetes env.
3. understand the `helm-generated.sh` and PR https://github.com/Alluxio/alluxio/pull/13234 together with the comments.

@LuQQiu has a PR https://github.com/Alluxio/alluxio/pull/13234
https://github.com/Alluxio/alluxio/pull/13234/commits
In the first commit, she added the Standalone Fuse helm yarm example auto-generated by the `helm-generate.sh ` with some custom changes.
In the second commit, she added the actual changes she wants https://github.com/Alluxio/alluxio/pull/13234/commits/7c2d2a2b11571d4e91b98ce0e9ce714eeb411053

First, change the `helm-generate.sh` script to reflect the changes of https://github.com/Alluxio/alluxio/pull/13234/commits/7c2d2a2b11571d4e91b98ce0e9ce714eeb411053
to support worker Fuse instead of standalone fuse.

Second, change the `helm-generate.sh` to support both WorkerFuse and StandaloneFuse mode.

Time estimate:
1 month

**Comment by ssz1997** [comment]
/assign @ssz1997 

@LuQQiu If user run helm-generate.sh, 
    1. Are we having two yaml files for the worker (one with Fuse and one without), or only one file with Fuse?
    2. StandaloneFuse template should always be generated regardless what user needs, right?

**Comment by LuQQiu** [comment]
helm-generate.sh
1. Yeah, we should be able to generate yaml files with/without worker fuse, maybe add a parameter to control that. But only one set of yaml files should be created based on the parameter.
2. emmmm... usually if users use worker fuse, standalone fuse is not needed, but there is no harm to include the standalone fuse yaml file as well.... do what you feel is easier.
