### ISSUE TITLE
Remove unused method alluxio.hadoop.HadoopUtils#toStringHadoopInputSplit

### ISSUE THREAD

**Issue by apc999** [Alluxio/new-contributor-tasks#602]
This method https://github.com/Alluxio/alluxio/blob/a98c6dbe312a125ee09daf4fa08c7498cd67e951/core/client/hdfs/src/main/java/alluxio/hadoop/HadoopUtils.java#L135
is unused across the codebase.

We can remove it

**Comment by dbw9580** [comment]
There're more methods in this class `HadoopUtils` that my IDE suggests are not used, e.g. `getAlluxioFileName` and `toStringHadoopFileSplit`. Should we remove them together, too?

**Comment by AgastyaSingh3292** [comment]
Can I work on it?

**Comment by apc999** [comment]
sure, go ahead Agastya

- Bin
