### ISSUE TITLE
The execution of command "alluxio fs count / " is very slow

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/new-contributor-tasks#604]
https://github.com/Alluxio/alluxio/issues/13158

1. See if `alluxio fs count / ` is slow with a directory with a large number of files for two consecutive runs. 
The second run should be much faster if the client-side metadata cache is enabled.
```
alluxio.user.metadata.cache.enabled=true
alluxio.user.metadata.cache.max.size=6000000
alluxio.user.metadata.cache.expiration.time=2day
```
2. If the second run is still slow, investigate why it's slow
3. See if it's possible to cache the slow part as well

**Comment by apc999** [comment]
close this issue. it has been explained in Alluxio/alluxio#13158
