### ISSUE TITLE
otel/opentelemetry-collector-dev:latest is not backward compatible

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/new-contributor-tasks#613]
Change all files under alluxio/integration/metrics
from 
```
otel/opentelemetry-collector-dev:latest
```
to
```
otel/opentelemetry-collector-dev:b24db545eb56e2ee7dcf6a8f3740ce49bb80608b
```

**Comment by LuQQiu** [comment]
@yuzhu FYI

**Comment by cyz14** [comment]
/assign @cyz14 
if this issue has not been assigned.

**Comment by LuQQiu** [comment]
@ddadaal Sorry that @cyz14 already created a PR and it's my problem that didn't merge it for a long time, thanks for all the effort, appreciate
