### ISSUE TITLE
Fix a grammar mistake in core/common/src/main/java/alluxio/conf/AlluxioConfiguration.java

### ISSUE THREAD

**Issue by apc999** [Alluxio/new-contributor-tasks#625]
https://github.com/Alluxio/alluxio/blob/a2854b46c63ff63099be7223a499682231d04b38/core/common/src/main/java/alluxio/conf/AlluxioConfiguration.java#L230

"whether or not the configuration has been merged with cluster defaults" -> "whether the configuration has been merged with cluster defaults"

**Comment by Sucran** [comment]
@apc999  I found this issue had been resolved, I check the context of master branch of Alluxio.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/6975465/161181818-0e3d2e48-a22c-43c0-9053-9ba47b9abec5.png">

**Comment by apc999** [comment]
Thanks for letting us know. Close this ticket then
