### ISSUE TITLE
Fix logging message in core/server/master/src/main/java/alluxio/master/backup/BackupWorkerRole.java

### ISSUE THREAD

**Issue by apc999** [Alluxio/new-contributor-tasks#630]
In https://github.com/Alluxio/alluxio/blob/2e8258c10319d53bc9e70ee7c7ead04d0b46c999/core/server/master/src/main/java/alluxio/master/backup/BackupWorkerRole.java#L378

```java
        LOG.warn("Failed to get backup-leader address. Error:{}. Attempt:{}", t.toString(),
            infiniteRetryPolicy.getAttemptCount());
```

**Comment by kyo-tom** [comment]
Fix https://github.com/Alluxio/new-contributor-tasks/issues/630 in https://github.com/Alluxio/alluxio/pull/15116
