### ISSUE TITLE
Update wording for copyFromLocal command in docs/_data/table/en/operation-command.yml

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/new-contributor-tasks#91]
Update
"Copy the specified file specified by "source path" to the path specified by "remote path". This command will fail if "remote path" already exists."
to
"Copy the file specified by "source path" to the path specified by "remote path". This command will fail if "remote path" already exists.

**Comment by gpang** [comment]
https://github.com/Alluxio/alluxio/pull/6510
