### ISSUE TITLE
Update wording for masterInfo command in docs/_data/table/en/operation-command.yml

### ISSUE THREAD

**Issue by aaudiber** [Alluxio/new-contributor-tasks#96]
Update
"Prints information regarding master fault tolerance such as leader address, list of master addresses, and the configured Zookeeper address."
to
"Print information regarding master fault tolerance such as leader address, list of master addresses, and configured Zookeeper address."

**Comment by gpang** [comment]
Addressed by: https://github.com/Alluxio/alluxio/pull/6400
